// greymemory.config.js — generated by greymemory init
// safe to commit — no API keys here, keys live in .env
import 'dotenv/config'
import GreyMemory from 'greymemory'
import Anthropic from '@anthropic-ai/sdk'

const anthropic = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY })

const extractor = async (messages) => {
  const res = await anthropic.messages.create({
    model: 'claude-haiku-4-5-20251001',
    max_tokens: 1000,
    messages: [{
      role: 'user',
      content: `Extract facts from this conversation as a flat JSON object.
Rules:
- keys are short snake_case strings
- values are strings only
- no nested objects, no arrays
- only factual information about the user
- respond with JSON only, no explanation

Conversation:
${JSON.stringify(messages)}`
    }]
  })
  const text = res.content[0].text.trim()
  return JSON.parse(text.replace(/```json|```/g, '').trim())
}

const embedder = async (text) => {
  const res = await fetch('http://localhost:11434/api/embeddings', {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'mxbai-embed-large',
      prompt: text
    })
  })
  const data = await res.json()
  return data.embedding
}

export default new GreyMemory({
  extractor,
  embedder,
  dir: '.greymemory',
  container: 'default'
})
